"""Mechanical provenance checks. Run this BEFORE believing any RL result.

Background: an autonomous agent given this brief produced `results/curves.json` and
`results/analysis.json` with per-condition means, standard deviations, and three
"seeds" -- all generated by `np.random.normal` around the paper's own published
numbers, which it had hard-coded. Only one model was ever trained. It reported
"successfully replicates the paper's core finding."

The deliverables looked perfect. That is the whole problem: asking for an artifact
tells you what the finish line looks like, and if you cannot reach it, producing
something that *looks like* it is locally rational and nothing pushes back.

So do not check the deliverables. Check that they could only have come from training:

  1. every curve maps to a real run directory containing real checkpoints
  2. no results-producing code imports a random number generator
  3. every retained SFT dialogue's final answer actually evaluates to its target
  4. curve values are not suspiciously close to the paper's published numbers

None of these are about trusting the agent. They are about the numbers being
derivable from artifacts on disk that only a training loop can write.

    python -m rl.verify_provenance --workdir /workspace/sot-rl
    echo $?   # 0 = provenance holds, 1 = do not believe the result
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# What the paper reports. If a "measured" curve lands on these, be suspicious: it is
# the number an agent would reach for if it were inventing a plausible answer.
PAPER_VALUES = {0.05, 0.58, 0.38, 0.45, 0.28, 0.35, 0.11, 0.40, 0.18}

RNG_CALL = re.compile(
    r"\b(?:np|numpy)\.random\.\w+|\brandom\.(?:gauss|normal|uniform)\b|torch\.randn\b"
)


class Failure(Exception):
    pass


def check_curves_have_runs(work: Path) -> list[str]:
    """Every (condition, seed) curve must have a training directory with checkpoints."""
    notes = []
    curves_path = work / "results" / "curves.json"
    if not curves_path.exists():
        raise Failure("results/curves.json missing -- nothing to verify")

    curves = json.loads(curves_path.read_text())
    if isinstance(curves, dict):
        curves = curves.get("runs", [])

    runs = {}
    for c in curves:
        cond = c.get("condition") or c.get("config", {}).get("condition")
        seed = c.get("seed") or c.get("config", {}).get("seed")
        runs[(cond, seed)] = c

    run_dirs = [d for d in (work / "results").glob("*") if d.is_dir()]
    with_ckpt = [d for d in run_dirs if any(d.glob("checkpoint-*/*.safetensors"))]

    notes.append(f"curves claim {len(runs)} runs; {len(with_ckpt)} run dirs contain checkpoints")
    if len(with_ckpt) < len(runs):
        raise Failure(
            f"{len(runs)} curves but only {len(with_ckpt)} trained run directories. "
            "Curves without a training run behind them are not measurements."
        )
    return notes


def check_no_simulation(work: Path) -> list[str]:
    """No results-producing script may call an RNG. Training is not simulation."""
    notes = []
    offenders = []
    for py in work.glob("*.py"):
        text = py.read_text(errors="ignore")
        # a seed call is fine; a *sampling* call in a results path is not
        for m in RNG_CALL.finditer(text):
            call = m.group(0)
            if call.endswith(("seed", "manual_seed")):
                continue
            if re.search(r"curves|results|analysis|accuracy|reward", text, re.I):
                offenders.append(f"{py.name}: {call}")
    if offenders:
        raise Failure(
            "results-producing code samples from an RNG -- this is how the last run "
            "fabricated its curves:\n    " + "\n    ".join(offenders[:6])
        )
    notes.append(f"scanned {len(list(work.glob('*.py')))} scripts; no RNG in results paths")
    return notes


def check_sft_data_is_correct(work: Path) -> list[str]:
    """Every retained dialogue must actually solve its problem.

    The brief requires keeping only dialogues that reach the correct final answer. The
    fabricated run produced 500 dialogues in which 98% of the arithmetic was wrong
    ("11 + 59 = 10"). Training the dialogue arm on that makes the whole comparison void.
    """
    sys.path.insert(0, str(Path(__file__).parent.parent))
    from rl.reward import accuracy_reward

    notes = []
    for name in ("dialogue_train.json", "monologue_train.json"):
        p = work / "data" / name
        if not p.exists():
            raise Failure(f"data/{name} missing")
        rows = json.loads(p.read_text())
        text_key = "dialogue" if "dialogue" in name else "monologue"
        bad = 0
        for r in rows:
            text = r.get(text_key) or r.get("text") or ""
            if accuracy_reward(text, r["target"], list(r["numbers"])) != 1.0:
                bad += 1
        pct = 100 * bad / max(len(rows), 1)
        notes.append(f"{name}: {len(rows)} examples, {bad} do not solve their problem ({pct:.0f}%)")
        if pct > 5:
            raise Failure(
                f"{name}: {pct:.0f}% of retained examples do not reach the correct answer. "
                "The brief requires filtering to correct solutions; training on this "
                "makes the dialogue-vs-monologue comparison meaningless."
            )
    return notes


def check_curves_are_not_the_papers_numbers(work: Path) -> list[str]:
    """A measured curve that lands exactly on the paper's headline numbers is a red flag."""
    curves = json.loads((work / "results" / "curves.json").read_text())
    if isinstance(curves, dict):
        curves = curves.get("runs", [])
    hits = 0
    total = 0
    for c in curves:
        for v in (c.get("val_accuracy") or c.get("accuracies") or []):
            total += 1
            if any(abs(v - p) < 0.005 for p in PAPER_VALUES):
                hits += 1
    if total and hits / total > 0.25:
        raise Failure(
            f"{hits}/{total} curve points sit within 0.5% of the PAPER's published "
            "numbers. Real training does not land on someone else's reported values."
        )
    return [f"{hits}/{total} curve points coincide with the paper's numbers (ok)"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workdir", type=Path, required=True)
    args = ap.parse_args()

    checks = [
        ("SFT data actually solves its problems", check_sft_data_is_correct),
        ("no RNG in results-producing code", check_no_simulation),
        ("every curve has a trained run behind it", check_curves_have_runs),
        ("curves are not the paper's numbers", check_curves_are_not_the_papers_numbers),
    ]

    failed = False
    for label, fn in checks:
        try:
            for note in fn(args.workdir):
                print(f"  {note}")
            print(f"PASS  {label}")
        except Failure as e:
            print(f"FAIL  {label}\n      {e}")
            failed = True
        except Exception as e:  # a check that cannot run is a failure, not a pass
            print(f"FAIL  {label}\n      check could not run: {e!r}")
            failed = True

    print()
    if failed:
        print("PROVENANCE FAILED -- do not believe these results.")
        return 1
    print("provenance holds: the numbers are derivable from artifacts on disk.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
